# Generated by Django 5.2 on 2025-04-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('volume', models.DecimalField(decimal_places=1, help_text='Объем двигателя в литрах', max_digits=4)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='catalog/images/cars/', verbose_name='Фото')),
            ],
        ),
    ]
