# Generated by Django 5.2 on 2025-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, default=1.6, help_text='Объем двигателя в литрах', max_digits=4),
        ),
    ]
