# Generated by Django 5.2 on 2025-04-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_car_engine_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='volume',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, help_text='Объем двигателя в литрах', max_digits=4),
        ),
    ]
